package xyz.trinitygames.Terfarmer.animals;

public abstract class Animal {
    String name;
    int value;
    int life;
    int income;

    /**
     * Get the name of the animal.
     * The format is "NAME (TYPE)".
     * @return string representation of the name
     */
    public abstract String getName();

    /**
     * Get the amount of money generated by the animal daily.
     * @return integer representation of the daily income
     */
    public int getIncome();

    /**
     * Original market value of the animal. Will decrease daily.
     * @return integer representation of the animal's value
     */
    public int getValue();

    /**
     * The amount of days the animal has left to live.
     * @return integer representation of the animal's remaining life spam
     */
    public int getLifetime();

    /**
     * Ages the animal by one day
     */
    public void age();
}
